ALTER TABLE cliente 
ADD CONSTRAINT FK_cliente
FOREIGN KEY (idCidade) 
REFERENCES cidade(idCidade) 
ON DELETE NO ACTION
ON UPDATE CASCADE

ALTER TABLE pedido 
ADD CONSTRAINT FK_pedido
FOREIGN KEY (idCliente)
REFERENCES cliente(idCliente)
ON DELETE NO ACTION
ON UPDATE CASCADE

ALTER TABLE responsavel_estoque
ADD CONSTRAINT FK_resp_est_usuario
FOREIGN KEY (idUsuario)
REFERENCES usuario(idUsuario)
ON DELETE NO ACTION
ON UPDATE CASCADE

ALTER TABLE responsavel_estoque
ADD CONSTRAINT FK_resp_est_prod
FOREIGN KEY (idProduto)
REFERENCES produto(idProduto)
ON DELETE NO ACTION
ON UPDATE CASCADE

ALTER TABLE pedido_item
ADD CONSTRAINT FK_ped_item_prod
FOREIGN KEY (idProduto)
REFERENCES produto(idProduto)
ON DELETE NO ACTION
ON UPDATE CASCADE

ALTER TABLE usuario
ADD CONSTRAINT FK_usuario_nivel
FOREIGN KEY (nivel)
REFERENCES nivel(idNivel)
ON DELETE NO ACTION
ON UPDATE CASCADE